<a href="https://colab.research.google.com/github/LucasMelvin15/Pytorch_deeplearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.3.0+cu121


**Introduction to Tensors**


Creating tensors

In [ ]:
#scalar
#represented by a single number. Also called rank zero tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
#Vector - Has both magnitude and direction. 1 dimension
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8],[1,2]])
matrix

tensor([[7, 8],
        [1, 2]])

In [ ]:
#ndim - number of dimensions
matrix.ndim

2

In [ ]:
matrix[1]

tensor([1, 2])

In [ ]:
matrix.shape
#2 by 2 matrix meaning 4 elements

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

### Random tensors
Why random tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers  -> look at data -> update random numbers  -> look at data -> update random numbers `

In [ ]:
#create a random tensor of size(3,4)
random_tensor = torch.rand(4,4)
random_tensor

tensor([[0.0612, 0.7912, 0.4827, 0.7529],
        [0.9199, 0.2160, 0.5958, 0.6691],
        [0.2535, 0.4326, 0.7724, 0.7573],
        [0.0522, 0.0537, 0.7893, 0.3290]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3)) #height,width, color channels(R,G,B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and ones

In [ ]:
#Create a tensor of zeros

zeros = torch.zeros(size=(4,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of ones

ones = torch.ones(size = (4,4))
ones
ones* random_tensor

tensor([[0.0612, 0.7912, 0.4827, 0.7529],
        [0.9199, 0.2160, 0.5958, 0.6691],
        [0.2535, 0.4326, 0.7724, 0.7573],
        [0.0522, 0.0537, 0.7893, 0.3290]])

### Creating a range of tensors and tensors-like

In [ ]:
#Use torch.arange()

one_to_ten= torch.arange(start= 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype= None, #what datatype is the tensor eg float32 or float16
                               device = None, #what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from Tensors (Tensor attributes)
1. Tensor not right data type = to get tensor data type use `tensor.dtype`
2. Tensor not right shape = to get shape from a tensor use `tensor.shape`
3. Tensor not the right device - to get device from tensor use `tensor.device`

In [ ]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8590, 0.5327, 0.0135, 0.4913],
        [0.1619, 0.1779, 0.7247, 0.4350],
        [0.7395, 0.9275, 0.3937, 0.2191]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Datatype of tensor: {some_tensor.device}")
print(f"Datatype of tensor: {some_tensor.shape}")
some_tensor.size()

tensor([[0.8590, 0.5327, 0.0135, 0.4913],
        [0.1619, 0.1779, 0.7247, 0.4350],
        [0.7395, 0.9275, 0.3937, 0.2191]])
Datatype of tensor: torch.float32
Datatype of tensor: cpu
Datatype of tensor: torch.Size([3, 4])


torch.Size([3, 4])

### Manipulating tensors (Tensor operations)

Tensor operations include:

1. Addition
2. Subtraction
3. Multiplication(element-wise)
4.Division
5.Matrix multiplication

In [ ]:
#create a tensor and add 10 to it
tensor = torch.tensor ([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
#Multiply a tensor
tensor * 10

tensor([10, 20, 30])

In [ ]:
#Reassign and subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#try out Pytorch in-built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
#Matrix multiplication
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor1.shape


torch.Size([3, 2])

In [ ]:
tensor2=  torch.tensor([[7,8],[9,10],[11,12]])
tensor2.shape

torch.Size([3, 2])

In [ ]:
tensor2=  torch.tensor([[7,8],[9,10],[11,12]])
torch.matmul(tensor1,tensor2)
torch.mm(tensor1,tensor2) # it is the same as matmul

#Rules for matrix multiplication
1.Inner dimensions must match


*  ` (3,2) @ (3,2)` - wont work
*   `(3,2) @ (2,3)` - will work
*    `(2,3) @ (3,2)` - will work
2. The resulting matrix has the shape of the outer dimensions
* `(3,2) @ (2,3)` -> `(3,3)`
* `(2,3) @ (3,2)` -> `(2,2)`


In [ ]:
#Element wise multiplication
torch.mul(tensor , tensor)

print(tensor, "*" , tensor)
print(f"Equals: { tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Finding the min, max, mean, sum etc( Tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the min
torch.min(x) ,  x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#find the mean - torch.mean() requires a tensor of float type32
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

### Finding positional min and max of tensors

In [ ]:
#position of the min value
torch.argmin(x)

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
#position of the max value
torch.argmax(x)

tensor(9)

In [ ]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - Reshapes an input tensor to a defined shape
*View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combines multiple tensors on top of each other (vstack) or side by side(hstack)
*Squeeze - Removes all `1` dimension from a tensor
*Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
#lets create a tensor
import torch
x = torch.arange(1., 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9) #adds a dimension ie extra square bracket. Has to be compatible with the original
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change the view
x_view = x.view(4,2)
x_view, x_view.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]),
 torch.Size([4, 2]))

In [ ]:
#Stack tensors on top of each other
#Concatenates a sequence of tensors along a new dimension.
z = torch.stack((x,x,x,x), dim=0)

z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.],
         [1., 2., 3., 4., 5., 6., 7., 8.],
         [1., 2., 3., 4., 5., 6., 7., 8.],
         [1., 2., 3., 4., 5., 6., 7., 8.]]),
 torch.Size([4, 8]))

In [ ]:
#Squeeze a tensor
#torch.squeeze removes all single dimensions from all target tensors
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")




Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
#Unsqueeze a tensor - adds an extra dimension to a target tensor
#torch.unsqueeze
x_squeezed = x_squeezed.unsqueeze(dim=0)
x_squeezed, x_squeezed.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [5]:
#Permute - Returns a view of the original tensor input with its dimensions permuted.
import torch
image_tensor = torch.rand(size=(224,224,3))

#print(f"Previous shape: {image_tensor}")
print(f"Previouss shape: {image_tensor.shape}")

permuted_image_tensor = image_tensor.permute(2,0,1)
#print(f"\nNew tensor: {permuted_image_tensor}")
print(f"New shape: {permuted_image_tensor.shape}")


Previouss shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


###Indexing (Selecting data from tensors)
Indexing with pytorch is similar to indexing with Numpy

In [7]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [8]:
#Indexing the new tensor - index [0] gives everything inside the first square brackets
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
#lets index the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [52]:
#let's index the inner most bracket (dim =3) - This gives the individual numbers in the matrix
x[0][0][0]

tensor(1)

In [27]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [28]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1 ]

tensor([[2, 5, 8]])

In [29]:
#Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension

x[:, 1, 1]

tensor([5])

In [31]:
# Get all 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [34]:
# Index on x to return 9
x[:,2, 2]

tensor([9])

In [35]:
#index on x to return 3,6,9
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch tensors and Numpy
Numpy is a popular scientific python numerical computing library.

And because of this, Pytorch has functionality to interact with it

* Data in Numpy, want in Pytorch tensor ->` torch.from_numpy(ndarry)`
*Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`


In [38]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) .#type(torch.float32)
array, tensor
#numpy default datatype is float64 hence its reflected to pytorch as float64

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [39]:
#change the value of the array. What happens to tensor ?

array = array + 1
array, tensor

#the value of the tensor that is stored in memory doesn't change

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [44]:
#Tensor to Numpy array
tensor = torch.ones(7)
numpy_array = torch.Tensor.numpy(tensor)
tensor, numpy_array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [45]:
#change the tensor. What happens to the numpy
tensor = tensor + 1
tensor, numpy_array
 # the value of the numpy array stored in memory does not change

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducibility - (Trying to make random out of random)

In short how a neural network learns

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again`

To reduce the randomness in neural networks and Pytorch comes the concept of a **random seed**

In [49]:
import torch

#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A )
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7738, 0.7984, 0.0399, 0.1616],
        [0.3621, 0.3677, 0.7368, 0.8719],
        [0.5711, 0.6607, 0.4952, 0.6124]])
tensor([[0.5867, 0.3184, 0.1906, 0.8331],
        [0.9393, 0.9549, 0.6782, 0.8157],
        [0.8463, 0.6149, 0.3885, 0.0161]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [51]:
#Lets make random but reproducible tensors

import torch

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

#random seed is passed before the rand method is called

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
