<a href="https://colab.research.google.com/github/LucasMelvin15/Pytorch_deeplearning/blob/main/Exercises/00Pytorch_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

##2.Create a random tensor with shape (7, 7).


In [3]:
random_tensor1 = torch.rand(7,7)
random_tensor1, random_tensor1.shape

(tensor([[0.2982, 0.2484, 0.7358, 0.3479, 0.9988, 0.8949, 0.1480],
         [0.8801, 0.9638, 0.9532, 0.9318, 0.9433, 0.4129, 0.7349],
         [0.8289, 0.7180, 0.2583, 0.1852, 0.9635, 0.9766, 0.3338],
         [0.7665, 0.4271, 0.3018, 0.6620, 0.0863, 0.8206, 0.5676],
         [0.1964, 0.7070, 0.2646, 0.1026, 0.4810, 0.6434, 0.6255],
         [0.9714, 0.9093, 0.9136, 0.3087, 0.3069, 0.3600, 0.2185],
         [0.5668, 0.8326, 0.0341, 0.7393, 0.8269, 0.2325, 0.3182]]),
 torch.Size([7, 7]))

##3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [6]:
random_tensor2 = torch.rand(size=(1,7))
torch.matmul(random_tensor1, random_tensor2.T)


tensor([[2.6220],
        [4.0125],
        [3.1349],
        [2.6249],
        [2.1336],
        [2.6172],
        [2.6489]])

##4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [24]:
#set a manual seed
torch.manual_seed(0)

#create two random tensors
X = torch.rand(size=(7,7))
Y = torch.rand(size=(1,7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))